### ISSUE TITLE
Definir y documentar procedimiento para agregar reglas para extendiendo la clase DataCleaner

### ISSUE THREAD

**Issue by plorenzatto** [gobabiertoAR/data-cleaner#22]
Deberia haber una manera estandar para realizar esto de manera que resulte sencillo implementar reglas nuevas para casos de filtrados particulares a la vez que tambien sea facil incorporarlas a la clase original.

**Comment by abenassi** [comment]
* Trabajar sobre template de audiencias: https://github.com/gobabiertoAR/datasets-portal/blob/master/audiencias/cleaner-audiencias.py
* Documentar los pasos para agregar un nuevo método de limpieza al DC en una sección "Contributing" del paquete. 
* Crear un template de método de limpieza de ejemplo para agregar, que muestre la estructura que tiene generalmente.
* Ver si debería portarse el template de audiencias al paquete del DataCleaner, como previa a su versión usable con command-line
